# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3.1
language: swift

env:
 global:
  - WORKSPACE='Example/RSPeekaboo.xcworkspace'
  - EXAMPLE_SCHEME='RSPeekaboo-Example'
  - IOS_DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=13.2'

# cache: cocoapods
podfile: Example/Podfile
xcode_sdk: iphonesimulator13.2
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod repo update
 - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace "$WORKSPACE"  -scheme "$EXAMPLE_SCHEME" -destination "$IOS_DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
